@echo off
cd /d "c:\Users\MICHAEL\Scale AX W.Space1 (DOE)\webapp\church-projector"
echo Adding files...
git add .
echo Committing...
git commit -m "branding: rename software to Creenly and update to v2.0.6"
echo Pushing to main...
git push origin main
echo Deleting old tag if exists...
git tag -d v2.0.6 2>nul
git push origin :refs/tags/v2.0.6 2>nul
echo Creating new tag...
git tag v2.0.6
echo Pushing tag...
git push origin v2.0.6
echo Done!
pause
